# Generated by Django 5.0.2 on 2024-03-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('time_purchased', models.DateTimeField(auto_now_add=True)),
                ('expense_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.expense_type')),
            ],
        ),
    ]
