# Generated by Django 5.0.2 on 2024-03-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expense_type',
        ),
        migrations.DeleteModel(
            name='Expense_Type',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
