# Generated by Django 5.0.2 on 2024-03-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_item_expense_type_delete_expense_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phonenumber',
        ),
    ]
