# Generated by Django 5.0.2 on 2024-03-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_item_quantity_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time_purchased',
            field=models.DateField(auto_now_add=True),
        ),
    ]
